apiVersion: v2
appVersion: 2.0.0
description: NL-Portal Configuration Panel Helm chart to be used in Kubernetes clusters.
kubeVersion: ">=1.23.0"
name: nl-portal-configpanel-backend
type: application
version: 3.0.0
